"""initial_db

Revision ID: 88cae22b7283
Revises: 
Create Date: 2023-01-22 15:30:09.645436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cae22b7283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('number_of_transitions', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_model_created_at'), 'url_model', ['created_at'], unique=False)
    op.create_index(op.f('ix_url_model_id'), 'url_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_model_id'), table_name='url_model')
    op.drop_index(op.f('ix_url_model_created_at'), table_name='url_model')
    op.drop_table('url_model')
    # ### end Alembic commands ###
